### ISSUE TITLE
Shrink Ray does not work with ModelReplacementAPI

### ISSUE THREAD

**Issue by geekygamer211** [MehimoNemo/LethalCompanyShrinkRay#93]
Same as thread. Need support / integration with ModelReplacementAPI

**Comment by AboveFire** [comment]
I've fixed it to work with ModelReplacementAPI. It works with the ModelReplacementAPI mods I've tried including but not limited to this one:
https://thunderstore.io/c/lethal-company/p/45x_Dev/45x_Anime_Models/

Can you post the ones that don't work so that I can test them out and see if this can be fixed.

**Comment by geekygamer211** [comment]
The mod we're using is LethalCreature https://thunderstore.io/c/lethal-company/p/DarnHyena/LethalCreature/

**Comment by AboveFire** [comment]
Should be fixed when next version is pushed. LethalCreatures sometimes rebuild it's model in runtime and this made our mod loose track of it. WIth the fix it reattaches itself at the end of every scaling so it should allow to keep track of it effectively.

**Comment by geekygamer211** [comment]
Seems mostly fixed with the update! Models shrink and grow as they should, but whenever somebody joins the lobby it resets everybody's models to default size. Using the shrinkray again causes the model to update. 
we found that if someone is already at minimum size when this bug happens, using the shrinkray again causes the player to poof away visually, while leaving the player stuck in limbo where they are unable to move or be interacted with.

**Comment by AboveFire** [comment]
Mmmhhh, interesting, it's most likely due to the fact that LethalCreature is one of the only ModelReplacementApi mods I know of that applies it's model on join instead of on costume swap. I'll test it out a bit more and will most likely fix it for the next version. Shouldn't be too hard to fix, just needs additional safeguards.

**Comment by NiroDev** [comment]
Fixed in 1.2.0. will close this on confirmation

**Comment by NiroDev** [comment]
Likely fixed. Will reopen if there are still issues.
