### ISSUE TITLE
[Idea] Tiny Cruiser

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#99]
make cruiser tiny, when shrinking the cruiser, that also shrinking all the things inside the cruiser

**Comment by NiroDev** [comment]
Shrinking the cruiser worked (nearly) out of the box. Also made a patch that locally resizes you relative to the cruiser size so that your view is still normal and the cruiser useable. There is just one tiny thing that prevents me from releasing this...

... the cruiser always explodes after being ignited so far, no matter what i patch/change/adjust.
Once i figured out how to solve this i'll push 1.4
